name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer format release tag, i.e. 0.23.4'
        required: true

jobs:
  create:
    name: Pepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Bump Version
        id: prepare_release
        run: |
          git checkout -b v${{ github.event.inputs.version }}-release
          sed -i -e 's/Version = ".*"/Version = "'"${{ github.event.inputs.version }}"'"/' go/cmd/dolt/dolt.go

      - uses: EndBug/add-and-commit@v5
        with:
          message: Bumped version to ${{ github.event.inputs.version }} for release
          branch: v${{ github.event.inputs.version }}-release
          add: go/cmd/dolt/dolt.go
          tag: 'v${{ github.event.inputs.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
